# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - edulink

on:
  push:
    branches:
      - main
    # This line ensures the workflow ONLY runs when you change backend code
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          # Using Node.js 20.x as requested
          node-version: '20.x'

      - name: npm install and build
        # THIS IS THE KEY FIX: All commands now run inside the ./backend folder
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # THIS IS THE SECOND FIX: We are only uploading the backend folder
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for login with OIDC

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FB0E0CC13E3F42878E0E4C3F0AC79FB4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BF92AE1DFD0F427BBE991E60F4B83262 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5DC2434BE8F24AF9BF8CDC896F3F1B9E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'edulink'
          slot-name: 'Production'
          # The package is now correctly just the backend code
          package: .
