# This is the full and correct content for your backend deployment workflow file.

name: Build and deploy Node.js app to Azure Web App - edulink

on:
  push:
    branches:
      - main
    # This ensures the workflow only runs when you change backend code
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          # Corrected to Node.js 20.x
          node-version: '22.x'

      - name: npm install and build
        # This command group runs entirely inside the backend folder
        run: |
          cd backend
          npm install
          npm run build --if-present
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # Explicitly upload ONLY the backend folder
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for login with OIDC

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8C360E1FA42848748B35E8DFD6CC5016 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3B611E8889994DD5A314CC6421AB1473 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7405661EB0D64896BD05AFF5838CF0F7 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'edulink'
          slot-name: 'Production'
          # The package is the downloaded artifact, which is the backend folder
          package: .
